name: Build Android Debug APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 12266719
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: true
        packages: |
          platform-tools
          platforms;android-30
          build-tools;30.0.3

    - name: Grant gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew clean assembleDebug --no-daemon

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: showcase-apk
        path: |
          **/build/outputs/**/*.apk
