name: Build Android Debug APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME_11: /usr/lib/jvm/java-11-openjdk-amd64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Install Android SDK tools
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        build-tools: "30.0.3"
        components: "platform-tools;platforms;build-tools;emulator;extras;ndk;ndk-bundle"

    - name: Grant gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew clean assembleDebug --no-daemon
      # 若需要 release 构建且你有签名配置，可改为 assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: showcase-apk
        path: |
          **/build/outputs/**/*.apk
